// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package protobufpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message represents what is the purpose of object
type Message int32

const (
	Message_MESSAGE_INVALID            Message = 0
	Message_MESSAGE_CREATE_USER        Message = 1
	Message_MESSAGE_READ_USER_BY_EMAIL Message = 2
	Message_MESSAGE_READ_USER_BY_ID    Message = 3
	Message_MESSAGE_CREATE_PRODUCT     Message = 10
)

var Message_name = map[int32]string{
	0:  "MESSAGE_INVALID",
	1:  "MESSAGE_CREATE_USER",
	2:  "MESSAGE_READ_USER_BY_EMAIL",
	3:  "MESSAGE_READ_USER_BY_ID",
	10: "MESSAGE_CREATE_PRODUCT",
}

var Message_value = map[string]int32{
	"MESSAGE_INVALID":            0,
	"MESSAGE_CREATE_USER":        1,
	"MESSAGE_READ_USER_BY_EMAIL": 2,
	"MESSAGE_READ_USER_BY_ID":    3,
	"MESSAGE_CREATE_PRODUCT":     10,
}

func (x Message) String() string {
	return proto.EnumName(Message_name, int32(x))
}

func (Message) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

// Object represents table/struct
//
// [USER], [USER PWD], [WALLET], [MARKET], [ASSET], and [TNX]
type Object int32

const (
	Object_OBJECT_INVALID       Object = 0
	Object_OBJECT_USER          Object = 1
	Object_OBJECT_PRODUCT       Object = 2
	Object_OBJECT_PRODUCT_GROUP Object = 3
	Object_OBJECT_UNIT          Object = 4
)

var Object_name = map[int32]string{
	0: "OBJECT_INVALID",
	1: "OBJECT_USER",
	2: "OBJECT_PRODUCT",
	3: "OBJECT_PRODUCT_GROUP",
	4: "OBJECT_UNIT",
}

var Object_value = map[string]int32{
	"OBJECT_INVALID":       0,
	"OBJECT_USER":          1,
	"OBJECT_PRODUCT":       2,
	"OBJECT_PRODUCT_GROUP": 3,
	"OBJECT_UNIT":          4,
}

func (x Object) String() string {
	return proto.EnumName(Object_name, int32(x))
}

func (Object) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

// Action represents:
//
// STORE, QUERY
type Action int32

const (
	Action_ACTION_INVALID Action = 0
	Action_ACTION_CREATE  Action = 1
	Action_ACTION_READ    Action = 2
	Action_ACTION_UPDATE  Action = 3
	Action_ACTION_DELETE  Action = 4
)

var Action_name = map[int32]string{
	0: "ACTION_INVALID",
	1: "ACTION_CREATE",
	2: "ACTION_READ",
	3: "ACTION_UPDATE",
	4: "ACTION_DELETE",
}

var Action_value = map[string]int32{
	"ACTION_INVALID": 0,
	"ACTION_CREATE":  1,
	"ACTION_READ":    2,
	"ACTION_UPDATE":  3,
	"ACTION_DELETE":  4,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{2}
}

// Ex:
//
// [action]   ----  [object]   -----  [message]
// query             wallet           user_wallet
type BaseReq struct {
	Action               Action   `protobuf:"varint,1,opt,name=action,proto3,enum=protobuf.Action" json:"action,omitempty"`
	ObjectType           Object   `protobuf:"varint,2,opt,name=object_type,json=objectType,proto3,enum=protobuf.Object" json:"object_type,omitempty"`
	Message              Message  `protobuf:"varint,3,opt,name=message,proto3,enum=protobuf.Message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseReq) Reset()         { *m = BaseReq{} }
func (m *BaseReq) String() string { return proto.CompactTextString(m) }
func (*BaseReq) ProtoMessage()    {}
func (*BaseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *BaseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseReq.Unmarshal(m, b)
}
func (m *BaseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseReq.Marshal(b, m, deterministic)
}
func (m *BaseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseReq.Merge(m, src)
}
func (m *BaseReq) XXX_Size() int {
	return xxx_messageInfo_BaseReq.Size(m)
}
func (m *BaseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseReq.DiscardUnknown(m)
}

var xxx_messageInfo_BaseReq proto.InternalMessageInfo

func (m *BaseReq) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_ACTION_INVALID
}

func (m *BaseReq) GetObjectType() Object {
	if m != nil {
		return m.ObjectType
	}
	return Object_OBJECT_INVALID
}

func (m *BaseReq) GetMessage() Message {
	if m != nil {
		return m.Message
	}
	return Message_MESSAGE_INVALID
}

func init() {
	proto.RegisterEnum("protobuf.Message", Message_name, Message_value)
	proto.RegisterEnum("protobuf.Object", Object_name, Object_value)
	proto.RegisterEnum("protobuf.Action", Action_name, Action_value)
	proto.RegisterType((*BaseReq)(nil), "protobuf.BaseReq")
}

func init() {
	proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150)
}

var fileDescriptor_db1b6b0986796150 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x5f, 0x4b, 0x83, 0x50,
	0x18, 0xc6, 0x3b, 0x3a, 0x5c, 0xbd, 0xab, 0xed, 0xec, 0x2c, 0x9a, 0x2c, 0x88, 0xe8, 0xa6, 0xb1,
	0x60, 0x50, 0x7d, 0x82, 0xa3, 0x1e, 0x86, 0xb1, 0x4d, 0x39, 0x3b, 0x06, 0x75, 0x23, 0x3a, 0xce,
	0xa2, 0x68, 0x69, 0x69, 0x17, 0xfb, 0x16, 0x41, 0x5f, 0x38, 0xfc, 0xd7, 0x6c, 0x74, 0xa5, 0xfe,
	0x9e, 0x9f, 0x8f, 0xef, 0xab, 0x02, 0x84, 0x41, 0x22, 0xc7, 0xf1, 0x47, 0x94, 0x46, 0x64, 0x3f,
	0x3f, 0x84, 0x9f, 0xab, 0x8b, 0x6f, 0x04, 0x4d, 0x23, 0x48, 0x24, 0x97, 0xef, 0x64, 0x08, 0x5a,
	0xb0, 0x4c, 0x9f, 0xa3, 0x37, 0x1d, 0x9d, 0xa3, 0x61, 0xfb, 0x06, 0x8f, 0x2b, 0x6d, 0x4c, 0x73,
	0xce, 0xcb, 0x9c, 0x5c, 0x43, 0x2b, 0x0a, 0x5f, 0xe4, 0x32, 0xf5, 0xd3, 0x4d, 0x2c, 0x75, 0x65,
	0x57, 0x77, 0xf2, 0x90, 0x43, 0x21, 0x89, 0x4d, 0x2c, 0xc9, 0x15, 0x34, 0xd7, 0x32, 0x49, 0x82,
	0x27, 0xa9, 0xab, 0xb9, 0xde, 0xdd, 0xea, 0xb3, 0x22, 0xe0, 0x95, 0x31, 0xfa, 0x42, 0xd0, 0x2c,
	0x21, 0xe9, 0x41, 0x67, 0xc6, 0x16, 0x0b, 0x3a, 0x61, 0xbe, 0x3d, 0xbf, 0xa7, 0x53, 0xdb, 0xc2,
	0x7b, 0xa4, 0x0f, 0xbd, 0x0a, 0x9a, 0x9c, 0x51, 0xc1, 0x7c, 0x6f, 0xc1, 0x38, 0x46, 0xe4, 0x0c,
	0x06, 0x55, 0xc0, 0x19, 0xb5, 0x72, 0xec, 0x1b, 0x0f, 0x3e, 0x9b, 0x51, 0x7b, 0x8a, 0x15, 0x72,
	0x0a, 0xfd, 0x7f, 0x73, 0xdb, 0xc2, 0x2a, 0x19, 0xc0, 0xc9, 0x4e, 0xab, 0xcb, 0x1d, 0xcb, 0x33,
	0x05, 0x86, 0xd1, 0x2b, 0x68, 0xc5, 0x56, 0x84, 0x40, 0xdb, 0x31, 0xee, 0x98, 0x29, 0x6a, 0xf3,
	0x74, 0xa0, 0x55, 0xb2, 0x72, 0x8e, 0xad, 0x54, 0x55, 0x28, 0x44, 0x87, 0xe3, 0xbf, 0xcc, 0x9f,
	0x70, 0xc7, 0x73, 0xb1, 0x5a, 0xbf, 0x7d, 0x6e, 0x0b, 0xdc, 0x18, 0xad, 0x40, 0x2b, 0x5e, 0x79,
	0x56, 0x44, 0x4d, 0x61, 0x3b, 0xf3, 0xda, 0xd3, 0xba, 0x70, 0x54, 0xb2, 0x62, 0x4c, 0x8c, 0xb2,
	0x86, 0x12, 0x65, 0x6b, 0x61, 0xa5, 0xe6, 0x78, 0xae, 0x95, 0x39, 0x6a, 0x0d, 0x59, 0x6c, 0xca,
	0x04, 0xc3, 0x0d, 0xe3, 0x12, 0x0e, 0x97, 0xd1, 0xfa, 0xf7, 0x4b, 0x18, 0x07, 0xd9, 0xbf, 0xe0,
	0x66, 0x57, 0x2e, 0x7a, 0x84, 0x0a, 0xc7, 0x61, 0xa8, 0xe5, 0xe7, 0xb7, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x35, 0x5a, 0x8a, 0x6f, 0x46, 0x02, 0x00, 0x00,
}
