// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package protobufpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message represents what is the purpose of object
type Message int32

const (
	Message_MESSAGE_INVALID               Message = 0
	Message_MESSAGE_CREATE_USER           Message = 1
	Message_MESSAGE_READ_USER_BY_EMAIL    Message = 2
	Message_MESSAGE_READ_USER_BY_ID       Message = 3
	Message_MESSAGE_UPDATE_USER           Message = 4
	Message_MESSAGE_CHANGE_PWD_USER       Message = 5
	Message_MESSAGE_DELETE_USER_BY_ID     Message = 6
	Message_MESSAGE_DELETE_USER_BY_EMAIL  Message = 7
	Message_MESSAGE_CREATE_EMAIL_TEMPLATE Message = 11
	Message_MESSAGE_READ_EMAIL_TEMPLATE   Message = 12
	Message_MESSAGE_UPDATE_EMAIL_TEMPLATE Message = 13
	Message_MESSAGE_DELETE_EMAIL_TEMPLATE Message = 14
	Message_MESSAGE_LIST_EMAIL_TEMPLATE   Message = 15
	Message_MESSAGE_CREATE_PRODUCT        Message = 20
)

var Message_name = map[int32]string{
	0:  "MESSAGE_INVALID",
	1:  "MESSAGE_CREATE_USER",
	2:  "MESSAGE_READ_USER_BY_EMAIL",
	3:  "MESSAGE_READ_USER_BY_ID",
	4:  "MESSAGE_UPDATE_USER",
	5:  "MESSAGE_CHANGE_PWD_USER",
	6:  "MESSAGE_DELETE_USER_BY_ID",
	7:  "MESSAGE_DELETE_USER_BY_EMAIL",
	11: "MESSAGE_CREATE_EMAIL_TEMPLATE",
	12: "MESSAGE_READ_EMAIL_TEMPLATE",
	13: "MESSAGE_UPDATE_EMAIL_TEMPLATE",
	14: "MESSAGE_DELETE_EMAIL_TEMPLATE",
	15: "MESSAGE_LIST_EMAIL_TEMPLATE",
	20: "MESSAGE_CREATE_PRODUCT",
}

var Message_value = map[string]int32{
	"MESSAGE_INVALID":               0,
	"MESSAGE_CREATE_USER":           1,
	"MESSAGE_READ_USER_BY_EMAIL":    2,
	"MESSAGE_READ_USER_BY_ID":       3,
	"MESSAGE_UPDATE_USER":           4,
	"MESSAGE_CHANGE_PWD_USER":       5,
	"MESSAGE_DELETE_USER_BY_ID":     6,
	"MESSAGE_DELETE_USER_BY_EMAIL":  7,
	"MESSAGE_CREATE_EMAIL_TEMPLATE": 11,
	"MESSAGE_READ_EMAIL_TEMPLATE":   12,
	"MESSAGE_UPDATE_EMAIL_TEMPLATE": 13,
	"MESSAGE_DELETE_EMAIL_TEMPLATE": 14,
	"MESSAGE_LIST_EMAIL_TEMPLATE":   15,
	"MESSAGE_CREATE_PRODUCT":        20,
}

func (x Message) String() string {
	return proto.EnumName(Message_name, int32(x))
}

func (Message) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

// Object represents table/struct
//
// [USER], [USER PWD], [WALLET], [MARKET], [ASSET], and [TNX]
type Object int32

const (
	Object_OBJECT_INVALID        Object = 0
	Object_OBJECT_USER           Object = 1
	Object_OBJECT_PRODUCT        Object = 2
	Object_OBJECT_PRODUCT_GROUP  Object = 3
	Object_OBJECT_UNIT           Object = 4
	Object_OBJECT_EMAIL_TEMPLATE Object = 5
)

var Object_name = map[int32]string{
	0: "OBJECT_INVALID",
	1: "OBJECT_USER",
	2: "OBJECT_PRODUCT",
	3: "OBJECT_PRODUCT_GROUP",
	4: "OBJECT_UNIT",
	5: "OBJECT_EMAIL_TEMPLATE",
}

var Object_value = map[string]int32{
	"OBJECT_INVALID":        0,
	"OBJECT_USER":           1,
	"OBJECT_PRODUCT":        2,
	"OBJECT_PRODUCT_GROUP":  3,
	"OBJECT_UNIT":           4,
	"OBJECT_EMAIL_TEMPLATE": 5,
}

func (x Object) String() string {
	return proto.EnumName(Object_name, int32(x))
}

func (Object) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

// Action represents:
//
// STORE, QUERY
type Action int32

const (
	Action_ACTION_INVALID Action = 0
	Action_ACTION_CREATE  Action = 1
	Action_ACTION_READ    Action = 2
	Action_ACTION_UPDATE  Action = 3
	Action_ACTION_DELETE  Action = 4
	Action_ACTION_LIST    Action = 5
)

var Action_name = map[int32]string{
	0: "ACTION_INVALID",
	1: "ACTION_CREATE",
	2: "ACTION_READ",
	3: "ACTION_UPDATE",
	4: "ACTION_DELETE",
	5: "ACTION_LIST",
}

var Action_value = map[string]int32{
	"ACTION_INVALID": 0,
	"ACTION_CREATE":  1,
	"ACTION_READ":    2,
	"ACTION_UPDATE":  3,
	"ACTION_DELETE":  4,
	"ACTION_LIST":    5,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{2}
}

// Ex:
//
// [action]   ----  [object]   -----  [message]
// query             wallet           user_wallet
type BaseReq struct {
	Action               Action   `protobuf:"varint,1,opt,name=action,proto3,enum=protobuf.Action" json:"action,omitempty"`
	ObjectType           Object   `protobuf:"varint,2,opt,name=object_type,json=objectType,proto3,enum=protobuf.Object" json:"object_type,omitempty"`
	Message              Message  `protobuf:"varint,3,opt,name=message,proto3,enum=protobuf.Message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseReq) Reset()         { *m = BaseReq{} }
func (m *BaseReq) String() string { return proto.CompactTextString(m) }
func (*BaseReq) ProtoMessage()    {}
func (*BaseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *BaseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseReq.Unmarshal(m, b)
}
func (m *BaseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseReq.Marshal(b, m, deterministic)
}
func (m *BaseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseReq.Merge(m, src)
}
func (m *BaseReq) XXX_Size() int {
	return xxx_messageInfo_BaseReq.Size(m)
}
func (m *BaseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseReq.DiscardUnknown(m)
}

var xxx_messageInfo_BaseReq proto.InternalMessageInfo

func (m *BaseReq) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_ACTION_INVALID
}

func (m *BaseReq) GetObjectType() Object {
	if m != nil {
		return m.ObjectType
	}
	return Object_OBJECT_INVALID
}

func (m *BaseReq) GetMessage() Message {
	if m != nil {
		return m.Message
	}
	return Message_MESSAGE_INVALID
}

func init() {
	proto.RegisterEnum("protobuf.Message", Message_name, Message_value)
	proto.RegisterEnum("protobuf.Object", Object_name, Object_value)
	proto.RegisterEnum("protobuf.Action", Action_name, Action_value)
	proto.RegisterType((*BaseReq)(nil), "protobuf.BaseReq")
}

func init() {
	proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150)
}

var fileDescriptor_db1b6b0986796150 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x49, 0xd3, 0xa6, 0x70, 0xba, 0xb5, 0xde, 0xd9, 0x60, 0xdd, 0xc6, 0x60, 0x70, 0xc3,
	0x54, 0xa4, 0x4a, 0xc0, 0x13, 0x38, 0x89, 0x55, 0x82, 0xd2, 0x26, 0x72, 0x5d, 0x10, 0xdc, 0x58,
	0x4d, 0x65, 0x10, 0x48, 0x23, 0x85, 0x16, 0xa1, 0x3d, 0x01, 0x0f, 0xc0, 0x9b, 0xf0, 0x84, 0x28,
	0xb1, 0xb3, 0xb9, 0x16, 0x5c, 0x25, 0xf9, 0xff, 0xef, 0x1c, 0xff, 0x3e, 0x76, 0x00, 0x8a, 0xe5,
	0x46, 0x8d, 0xd7, 0xdf, 0xcb, 0x6d, 0x89, 0x77, 0xeb, 0x47, 0xf1, 0xe3, 0xe3, 0xd3, 0xdf, 0x1e,
	0x74, 0xc3, 0xe5, 0x46, 0x71, 0xf5, 0x0d, 0x2f, 0x21, 0x58, 0xae, 0xb6, 0x9f, 0xcb, 0xaf, 0x43,
	0xef, 0xc2, 0xbb, 0xec, 0xbf, 0x24, 0xe3, 0x06, 0x1b, 0xd3, 0x5a, 0xe7, 0xc6, 0xc7, 0x17, 0xd0,
	0x2b, 0x8b, 0x2f, 0x6a, 0xb5, 0x95, 0xdb, 0xeb, 0xb5, 0x1a, 0xb6, 0x5c, 0x3c, 0xab, 0x4d, 0x0e,
	0x1a, 0x12, 0xd7, 0x6b, 0x85, 0xcf, 0xa1, 0x7b, 0xa5, 0x36, 0x9b, 0xe5, 0x27, 0x35, 0xf4, 0x6b,
	0xfc, 0xe0, 0x16, 0x9f, 0x6a, 0x83, 0x37, 0xc4, 0xe8, 0x8f, 0x0f, 0x5d, 0x23, 0xe2, 0x21, 0x0c,
	0xa6, 0x6c, 0x3e, 0xa7, 0x13, 0x26, 0x93, 0xd9, 0x5b, 0x9a, 0x26, 0x31, 0xb9, 0x83, 0xc7, 0x70,
	0xd8, 0x88, 0x11, 0x67, 0x54, 0x30, 0xb9, 0x98, 0x33, 0x4e, 0x3c, 0x7c, 0x04, 0xa7, 0x8d, 0xc1,
	0x19, 0x8d, 0x6b, 0x59, 0x86, 0xef, 0x25, 0x9b, 0xd2, 0x24, 0x25, 0x2d, 0x3c, 0x83, 0xe3, 0x7f,
	0xfa, 0x49, 0x4c, 0x7c, 0xbb, 0xeb, 0x22, 0x8f, 0x6f, 0xba, 0xb6, 0xed, 0xaa, 0xe8, 0x35, 0x9d,
	0x4d, 0x98, 0xcc, 0xdf, 0xe9, 0x5a, 0xd2, 0xc1, 0x73, 0x38, 0x69, 0xcc, 0x98, 0xa5, 0xcc, 0x54,
	0x99, 0xa6, 0x01, 0x5e, 0xc0, 0xc3, 0xff, 0xd8, 0x3a, 0x53, 0x17, 0x9f, 0xc0, 0xb9, 0xb3, 0x99,
	0xda, 0x91, 0x82, 0x4d, 0xf3, 0x94, 0x0a, 0x46, 0x7a, 0xf8, 0x18, 0xce, 0x76, 0x62, 0x3b, 0xc0,
	0x9e, 0xdd, 0xc3, 0x44, 0x77, 0x90, 0x7d, 0x1b, 0x31, 0x41, 0x1c, 0xa4, 0x6f, 0x2f, 0x93, 0x26,
	0x73, 0xe1, 0x02, 0x03, 0x3c, 0x85, 0x07, 0x4e, 0xd4, 0x9c, 0x67, 0xf1, 0x22, 0x12, 0xe4, 0x68,
	0xf4, 0xcb, 0x83, 0x40, 0x1f, 0x3c, 0x22, 0xf4, 0xb3, 0xf0, 0x0d, 0x8b, 0x84, 0x75, 0x64, 0x03,
	0xe8, 0x19, 0xcd, 0x1c, 0xd5, 0x2d, 0xd4, 0xf4, 0x68, 0xe1, 0x10, 0x8e, 0x76, 0x35, 0x39, 0xe1,
	0xd9, 0x22, 0x27, 0xbe, 0x5d, 0x3e, 0x4b, 0x04, 0x69, 0xe3, 0x09, 0xdc, 0x37, 0x82, 0x93, 0xb2,
	0x33, 0xfa, 0x09, 0x81, 0xbe, 0xb0, 0xd5, 0x1a, 0x34, 0x12, 0x49, 0x36, 0xb3, 0x82, 0x1c, 0xc0,
	0xbe, 0xd1, 0xf4, 0x16, 0x88, 0x57, 0x35, 0x37, 0x52, 0x35, 0x5d, 0xd2, 0xb2, 0x18, 0x3d, 0x4d,
	0xe2, 0x5b, 0x92, 0x9e, 0x1e, 0x69, 0x5b, 0x65, 0xd5, 0xb4, 0x48, 0x27, 0x7c, 0x06, 0x7b, 0xab,
	0xf2, 0xea, 0xe6, 0x62, 0x87, 0xf7, 0xaa, 0x5f, 0x2b, 0xaf, 0xbe, 0x72, 0xef, 0x03, 0x34, 0xf2,
	0xba, 0x28, 0x82, 0xfa, 0xfd, 0xd5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xb5, 0x09, 0x4f,
	0x95, 0x03, 0x00, 0x00,
}
