// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email.base.proto

package protobufpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// EmailInfo : this object is used for sending email
//
// [data]: this value is based on templated id. Ex:
//
//    if template_id needs {{name}}, the data will be something like this one
//      {
//        "name": "phuong nguyen"
//      }
type EmailInfo struct {
	SenderName           string            `protobuf:"bytes,1,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderEmail          string            `protobuf:"bytes,2,opt,name=sender_email,json=senderEmail,proto3" json:"sender_email,omitempty"`
	TemplateId           string            `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Receivers            []*Receiver       `protobuf:"bytes,4,rep,name=receivers,proto3" json:"receivers,omitempty"`
	Data                 map[string]string `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EmailInfo) Reset()         { *m = EmailInfo{} }
func (m *EmailInfo) String() string { return proto.CompactTextString(m) }
func (*EmailInfo) ProtoMessage()    {}
func (*EmailInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_279db753f357c8c2, []int{0}
}

func (m *EmailInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailInfo.Unmarshal(m, b)
}
func (m *EmailInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailInfo.Marshal(b, m, deterministic)
}
func (m *EmailInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailInfo.Merge(m, src)
}
func (m *EmailInfo) XXX_Size() int {
	return xxx_messageInfo_EmailInfo.Size(m)
}
func (m *EmailInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EmailInfo proto.InternalMessageInfo

func (m *EmailInfo) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *EmailInfo) GetSenderEmail() string {
	if m != nil {
		return m.SenderEmail
	}
	return ""
}

func (m *EmailInfo) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *EmailInfo) GetReceivers() []*Receiver {
	if m != nil {
		return m.Receivers
	}
	return nil
}

func (m *EmailInfo) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type Receiver struct {
	ToName               string   `protobuf:"bytes,1,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	ToEmail              string   `protobuf:"bytes,2,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receiver) Reset()         { *m = Receiver{} }
func (m *Receiver) String() string { return proto.CompactTextString(m) }
func (*Receiver) ProtoMessage()    {}
func (*Receiver) Descriptor() ([]byte, []int) {
	return fileDescriptor_279db753f357c8c2, []int{1}
}

func (m *Receiver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receiver.Unmarshal(m, b)
}
func (m *Receiver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receiver.Marshal(b, m, deterministic)
}
func (m *Receiver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receiver.Merge(m, src)
}
func (m *Receiver) XXX_Size() int {
	return xxx_messageInfo_Receiver.Size(m)
}
func (m *Receiver) XXX_DiscardUnknown() {
	xxx_messageInfo_Receiver.DiscardUnknown(m)
}

var xxx_messageInfo_Receiver proto.InternalMessageInfo

func (m *Receiver) GetToName() string {
	if m != nil {
		return m.ToName
	}
	return ""
}

func (m *Receiver) GetToEmail() string {
	if m != nil {
		return m.ToEmail
	}
	return ""
}

func init() {
	proto.RegisterType((*EmailInfo)(nil), "protobuf.EmailInfo")
	proto.RegisterMapType((map[string]string)(nil), "protobuf.EmailInfo.DataEntry")
	proto.RegisterType((*Receiver)(nil), "protobuf.Receiver")
}

func init() {
	proto.RegisterFile("email.base.proto", fileDescriptor_279db753f357c8c2)
}

var fileDescriptor_279db753f357c8c2 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0xd2, 0x3f, 0xc9, 0xb4, 0x48, 0x59, 0x04, 0xa3, 0x20, 0xd6, 0x9e, 0x7a, 0x90,
	0xe0, 0x9f, 0x83, 0xe2, 0xc1, 0x43, 0xb1, 0x87, 0x5e, 0xa4, 0xe4, 0xe8, 0xa5, 0x4c, 0x9a, 0x29,
	0x04, 0xb3, 0xd9, 0xb0, 0x99, 0x16, 0xfa, 0x25, 0xfc, 0xcc, 0x92, 0xcd, 0x26, 0xb5, 0xa7, 0x4c,
	0xde, 0xfc, 0xf6, 0xf1, 0xe6, 0xc1, 0x84, 0x24, 0x66, 0x79, 0x94, 0x60, 0x45, 0x51, 0xa9, 0x15,
	0x2b, 0xe1, 0x9b, 0x4f, 0xb2, 0xdf, 0xcd, 0x7e, 0x5d, 0x08, 0x96, 0xf5, 0x7a, 0x55, 0xec, 0x94,
	0xb8, 0x83, 0x51, 0x45, 0x45, 0x4a, 0x7a, 0x53, 0xa0, 0xa4, 0xd0, 0x99, 0x3a, 0xf3, 0x20, 0x86,
	0x46, 0xfa, 0x42, 0x49, 0xe2, 0x1e, 0xc6, 0x16, 0x30, 0x9e, 0xa1, 0x6b, 0x08, 0xfb, 0xc8, 0xf8,
	0xd4, 0x1e, 0x4c, 0xb2, 0xcc, 0x91, 0x69, 0x93, 0xa5, 0xa1, 0xd7, 0x78, 0xb4, 0xd2, 0x2a, 0x15,
	0x8f, 0x10, 0x68, 0xda, 0x52, 0x76, 0x20, 0x5d, 0x85, 0xbd, 0xa9, 0x37, 0x1f, 0x3d, 0x8b, 0xa8,
	0x0d, 0x14, 0xc5, 0x76, 0x15, 0x9f, 0x20, 0xf1, 0x04, 0xbd, 0x14, 0x19, 0xc3, 0xbe, 0x81, 0x6f,
	0x4f, 0x70, 0x97, 0x3c, 0xfa, 0x44, 0xc6, 0x65, 0xc1, 0xfa, 0x18, 0x1b, 0xf4, 0xe6, 0x15, 0x82,
	0x4e, 0x12, 0x13, 0xf0, 0x7e, 0xe8, 0x68, 0xcf, 0xa9, 0x47, 0x71, 0x09, 0xfd, 0x03, 0xe6, 0x7b,
	0xb2, 0x07, 0x34, 0x3f, 0xef, 0xee, 0x9b, 0x33, 0xfb, 0x00, 0xbf, 0x8d, 0x20, 0xae, 0x60, 0xc8,
	0xea, 0x7f, 0x15, 0x03, 0x56, 0xa6, 0x86, 0x6b, 0xf0, 0x59, 0x9d, 0x55, 0x30, 0x64, 0x65, 0xc2,
	0x2c, 0x1e, 0x60, 0xbc, 0x55, 0xb2, 0x8b, 0xb8, 0xb8, 0x68, 0x64, 0xac, 0x68, 0x5d, 0x4b, 0x6b,
	0xe7, 0x1b, 0xda, 0x5d, 0x99, 0x24, 0x03, 0x33, 0xbf, 0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0x8e,
	0xb4, 0x94, 0x8a, 0xa3, 0x01, 0x00, 0x00,
}
