// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package protobufpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductGroup struct {
	GId                  string   `protobuf:"bytes,1,opt,name=g_id,json=gId,proto3" json:"g_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductGroup) Reset()         { *m = ProductGroup{} }
func (m *ProductGroup) String() string { return proto.CompactTextString(m) }
func (*ProductGroup) ProtoMessage()    {}
func (*ProductGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *ProductGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductGroup.Unmarshal(m, b)
}
func (m *ProductGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductGroup.Marshal(b, m, deterministic)
}
func (m *ProductGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductGroup.Merge(m, src)
}
func (m *ProductGroup) XXX_Size() int {
	return xxx_messageInfo_ProductGroup.Size(m)
}
func (m *ProductGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ProductGroup proto.InternalMessageInfo

func (m *ProductGroup) GetGId() string {
	if m != nil {
		return m.GId
	}
	return ""
}

func (m *ProductGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductGroup) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// CreateProductGroup
type CreateProductGroupReq struct {
	Request              *BaseReq      `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	ProductGroup         *ProductGroup `protobuf:"bytes,2,opt,name=productGroup,proto3" json:"productGroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateProductGroupReq) Reset()         { *m = CreateProductGroupReq{} }
func (m *CreateProductGroupReq) String() string { return proto.CompactTextString(m) }
func (*CreateProductGroupReq) ProtoMessage()    {}
func (*CreateProductGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *CreateProductGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductGroupReq.Unmarshal(m, b)
}
func (m *CreateProductGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductGroupReq.Marshal(b, m, deterministic)
}
func (m *CreateProductGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductGroupReq.Merge(m, src)
}
func (m *CreateProductGroupReq) XXX_Size() int {
	return xxx_messageInfo_CreateProductGroupReq.Size(m)
}
func (m *CreateProductGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductGroupReq proto.InternalMessageInfo

func (m *CreateProductGroupReq) GetRequest() *BaseReq {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *CreateProductGroupReq) GetProductGroup() *ProductGroup {
	if m != nil {
		return m.ProductGroup
	}
	return nil
}

type CreateProductGroupRes struct {
	Result               bool          `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ProductGroup         *ProductGroup `protobuf:"bytes,2,opt,name=productGroup,proto3" json:"productGroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateProductGroupRes) Reset()         { *m = CreateProductGroupRes{} }
func (m *CreateProductGroupRes) String() string { return proto.CompactTextString(m) }
func (*CreateProductGroupRes) ProtoMessage()    {}
func (*CreateProductGroupRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *CreateProductGroupRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductGroupRes.Unmarshal(m, b)
}
func (m *CreateProductGroupRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductGroupRes.Marshal(b, m, deterministic)
}
func (m *CreateProductGroupRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductGroupRes.Merge(m, src)
}
func (m *CreateProductGroupRes) XXX_Size() int {
	return xxx_messageInfo_CreateProductGroupRes.Size(m)
}
func (m *CreateProductGroupRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductGroupRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductGroupRes proto.InternalMessageInfo

func (m *CreateProductGroupRes) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *CreateProductGroupRes) GetProductGroup() *ProductGroup {
	if m != nil {
		return m.ProductGroup
	}
	return nil
}

func init() {
	proto.RegisterType((*ProductGroup)(nil), "protobuf.ProductGroup")
	proto.RegisterType((*CreateProductGroupReq)(nil), "protobuf.CreateProductGroupReq")
	proto.RegisterType((*CreateProductGroupRes)(nil), "protobuf.CreateProductGroupRes")
}

func init() {
	proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5)
}

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x14, 0x24, 0xb4, 0x2a, 0xe5, 0x25, 0x0c, 0x7d, 0x12, 0x55, 0xd4, 0x85, 0x2a, 0x13, 0x02, 0x29,
	0x43, 0xd8, 0x18, 0xc3, 0x80, 0xd8, 0x22, 0x33, 0x80, 0x58, 0x50, 0x12, 0xbf, 0x56, 0x11, 0xb4,
	0x76, 0xfc, 0xc1, 0xcc, 0x4f, 0x47, 0x38, 0x35, 0x4d, 0x45, 0x24, 0x06, 0x26, 0x3f, 0xdf, 0xdd,
	0xbb, 0x3b, 0xd9, 0x70, 0x26, 0x95, 0xe0, 0xb6, 0x36, 0xa9, 0x54, 0xc2, 0x08, 0x9c, 0xba, 0xa3,
	0xb2, 0xab, 0x05, 0x54, 0xa5, 0xa6, 0x0e, 0x4d, 0x9e, 0x20, 0x2a, 0x3a, 0xd9, 0xbd, 0x12, 0x56,
	0xe2, 0x0c, 0xc6, 0xeb, 0xd7, 0x86, 0xc7, 0xc1, 0x32, 0xb8, 0x3c, 0x65, 0xa3, 0xf5, 0x03, 0x47,
	0x84, 0xf1, 0xb6, 0xdc, 0x50, 0x7c, 0xec, 0x20, 0x37, 0xe3, 0x12, 0x42, 0x4e, 0xba, 0x56, 0x8d,
	0x34, 0x8d, 0xd8, 0xc6, 0x23, 0x47, 0xf5, 0xa1, 0xe4, 0x33, 0x80, 0xf3, 0x3b, 0x45, 0xa5, 0xa1,
	0xbe, 0x3f, 0xa3, 0x16, 0xaf, 0xe1, 0x44, 0x51, 0x6b, 0x49, 0x1b, 0x97, 0x12, 0x66, 0xb3, 0xd4,
	0x57, 0x4b, 0xf3, 0x52, 0x13, 0xa3, 0x96, 0x79, 0x05, 0xde, 0x42, 0x24, 0x7b, 0xfb, 0xae, 0x44,
	0x98, 0xcd, 0xf7, 0x1b, 0x07, 0xee, 0x07, 0xda, 0xe4, 0x6d, 0xb8, 0x81, 0xc6, 0x39, 0x4c, 0x14,
	0x69, 0xfb, 0xde, 0x15, 0x98, 0xb2, 0xdd, 0xed, 0x3f, 0x61, 0xd9, 0x0a, 0x60, 0xc7, 0x3e, 0x7e,
	0xd4, 0xf8, 0x0c, 0xf8, 0x3b, 0x1a, 0x2f, 0xf6, 0x4e, 0x83, 0x4f, 0xb3, 0xf8, 0x43, 0xa0, 0x93,
	0xa3, 0xfc, 0x0a, 0xa2, 0x5a, 0x6c, 0x7e, 0x74, 0xb9, 0xff, 0xbe, 0xe2, 0x1b, 0x28, 0x82, 0x17,
	0xf0, 0x8c, 0xac, 0xaa, 0x89, 0x9b, 0x6f, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x20, 0xb1, 0xc5,
	0x56, 0x0a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductSvcClient is the client API for ProductSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductSvcClient interface {
	// Product group
	CreateProductGroup(ctx context.Context, in *CreateProductGroupReq, opts ...grpc.CallOption) (*CreateProductGroupRes, error)
}

type productSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewProductSvcClient(cc grpc.ClientConnInterface) ProductSvcClient {
	return &productSvcClient{cc}
}

func (c *productSvcClient) CreateProductGroup(ctx context.Context, in *CreateProductGroupReq, opts ...grpc.CallOption) (*CreateProductGroupRes, error) {
	out := new(CreateProductGroupRes)
	err := c.cc.Invoke(ctx, "/protobuf.ProductSvc/CreateProductGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductSvcServer is the server API for ProductSvc service.
type ProductSvcServer interface {
	// Product group
	CreateProductGroup(context.Context, *CreateProductGroupReq) (*CreateProductGroupRes, error)
}

// UnimplementedProductSvcServer can be embedded to have forward compatible implementations.
type UnimplementedProductSvcServer struct {
}

func (*UnimplementedProductSvcServer) CreateProductGroup(ctx context.Context, req *CreateProductGroupReq) (*CreateProductGroupRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductGroup not implemented")
}

func RegisterProductSvcServer(s *grpc.Server, srv ProductSvcServer) {
	s.RegisterService(&_ProductSvc_serviceDesc, srv)
}

func _ProductSvc_CreateProductGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductSvcServer).CreateProductGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ProductSvc/CreateProductGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductSvcServer).CreateProductGroup(ctx, req.(*CreateProductGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.ProductSvc",
	HandlerType: (*ProductSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProductGroup",
			Handler:    _ProductSvc_CreateProductGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
