// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protobufpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// UserInfo : store user information
type UserInfo struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Level                uint32   `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Role                 uint32   `protobuf:"varint,7,opt,name=role,proto3" json:"role,omitempty"`
	Keystore             string   `protobuf:"bytes,8,opt,name=keystore,proto3" json:"keystore,omitempty"`
	EnableNotification   bool     `protobuf:"varint,9,opt,name=enable_notification,json=enableNotification,proto3" json:"enable_notification,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *UserInfo) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *UserInfo) GetKeystore() string {
	if m != nil {
		return m.Keystore
	}
	return ""
}

func (m *UserInfo) GetEnableNotification() bool {
	if m != nil {
		return m.EnableNotification
	}
	return false
}

// CreateUser
type CreateUserReq struct {
	Req                  *BaseReq  `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	User                 *UserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateUserReq) Reset()         { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()    {}
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReq.Unmarshal(m, b)
}
func (m *CreateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReq.Marshal(b, m, deterministic)
}
func (m *CreateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReq.Merge(m, src)
}
func (m *CreateUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateUserReq.Size(m)
}
func (m *CreateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReq proto.InternalMessageInfo

func (m *CreateUserReq) GetReq() *BaseReq {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *CreateUserReq) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserRes struct {
	Result               bool      `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	User                 *UserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateUserRes) Reset()         { *m = CreateUserRes{} }
func (m *CreateUserRes) String() string { return proto.CompactTextString(m) }
func (*CreateUserRes) ProtoMessage()    {}
func (*CreateUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CreateUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRes.Unmarshal(m, b)
}
func (m *CreateUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRes.Marshal(b, m, deterministic)
}
func (m *CreateUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRes.Merge(m, src)
}
func (m *CreateUserRes) XXX_Size() int {
	return xxx_messageInfo_CreateUserRes.Size(m)
}
func (m *CreateUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRes proto.InternalMessageInfo

func (m *CreateUserRes) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *CreateUserRes) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

// ReadUser
type ReadUserReq struct {
	Req                  *BaseReq  `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	User                 *UserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReadUserReq) Reset()         { *m = ReadUserReq{} }
func (m *ReadUserReq) String() string { return proto.CompactTextString(m) }
func (*ReadUserReq) ProtoMessage()    {}
func (*ReadUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *ReadUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserReq.Unmarshal(m, b)
}
func (m *ReadUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserReq.Marshal(b, m, deterministic)
}
func (m *ReadUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserReq.Merge(m, src)
}
func (m *ReadUserReq) XXX_Size() int {
	return xxx_messageInfo_ReadUserReq.Size(m)
}
func (m *ReadUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserReq proto.InternalMessageInfo

func (m *ReadUserReq) GetReq() *BaseReq {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *ReadUserReq) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type ReadUserRes struct {
	Result               bool      `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	User                 *UserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReadUserRes) Reset()         { *m = ReadUserRes{} }
func (m *ReadUserRes) String() string { return proto.CompactTextString(m) }
func (*ReadUserRes) ProtoMessage()    {}
func (*ReadUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *ReadUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRes.Unmarshal(m, b)
}
func (m *ReadUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRes.Marshal(b, m, deterministic)
}
func (m *ReadUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRes.Merge(m, src)
}
func (m *ReadUserRes) XXX_Size() int {
	return xxx_messageInfo_ReadUserRes.Size(m)
}
func (m *ReadUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRes proto.InternalMessageInfo

func (m *ReadUserRes) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *ReadUserRes) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

// UpdateUser
type UpdateUserReq struct {
	Req                  *BaseReq  `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	User                 *UserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateUserReq) Reset()         { *m = UpdateUserReq{} }
func (m *UpdateUserReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserReq) ProtoMessage()    {}
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UpdateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserReq.Unmarshal(m, b)
}
func (m *UpdateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserReq.Marshal(b, m, deterministic)
}
func (m *UpdateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserReq.Merge(m, src)
}
func (m *UpdateUserReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserReq.Size(m)
}
func (m *UpdateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserReq proto.InternalMessageInfo

func (m *UpdateUserReq) GetReq() *BaseReq {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *UpdateUserReq) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRes struct {
	Result               bool      `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	User                 *UserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateUserRes) Reset()         { *m = UpdateUserRes{} }
func (m *UpdateUserRes) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRes) ProtoMessage()    {}
func (*UpdateUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UpdateUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRes.Unmarshal(m, b)
}
func (m *UpdateUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRes.Marshal(b, m, deterministic)
}
func (m *UpdateUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRes.Merge(m, src)
}
func (m *UpdateUserRes) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRes.Size(m)
}
func (m *UpdateUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRes proto.InternalMessageInfo

func (m *UpdateUserRes) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *UpdateUserRes) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

// DeleteUser
type DeleteUserReq struct {
	Req                  *BaseReq  `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	User                 *UserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeleteUserReq) Reset()         { *m = DeleteUserReq{} }
func (m *DeleteUserReq) String() string { return proto.CompactTextString(m) }
func (*DeleteUserReq) ProtoMessage()    {}
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *DeleteUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserReq.Unmarshal(m, b)
}
func (m *DeleteUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserReq.Marshal(b, m, deterministic)
}
func (m *DeleteUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserReq.Merge(m, src)
}
func (m *DeleteUserReq) XXX_Size() int {
	return xxx_messageInfo_DeleteUserReq.Size(m)
}
func (m *DeleteUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserReq proto.InternalMessageInfo

func (m *DeleteUserReq) GetReq() *BaseReq {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *DeleteUserReq) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRes struct {
	Result               bool      `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	User                 *UserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeleteUserRes) Reset()         { *m = DeleteUserRes{} }
func (m *DeleteUserRes) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRes) ProtoMessage()    {}
func (*DeleteUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *DeleteUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRes.Unmarshal(m, b)
}
func (m *DeleteUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRes.Marshal(b, m, deterministic)
}
func (m *DeleteUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRes.Merge(m, src)
}
func (m *DeleteUserRes) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRes.Size(m)
}
func (m *DeleteUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRes proto.InternalMessageInfo

func (m *DeleteUserRes) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *DeleteUserRes) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

// ChangePwd
type ChangePwdReq struct {
	Req                  *BaseReq `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	UserId               uint32   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPassword          string   `protobuf:"bytes,3,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,4,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePwdReq) Reset()         { *m = ChangePwdReq{} }
func (m *ChangePwdReq) String() string { return proto.CompactTextString(m) }
func (*ChangePwdReq) ProtoMessage()    {}
func (*ChangePwdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *ChangePwdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePwdReq.Unmarshal(m, b)
}
func (m *ChangePwdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePwdReq.Marshal(b, m, deterministic)
}
func (m *ChangePwdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePwdReq.Merge(m, src)
}
func (m *ChangePwdReq) XXX_Size() int {
	return xxx_messageInfo_ChangePwdReq.Size(m)
}
func (m *ChangePwdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePwdReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePwdReq proto.InternalMessageInfo

func (m *ChangePwdReq) GetReq() *BaseReq {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *ChangePwdReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChangePwdReq) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePwdReq) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePwdRes struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	TemplateId           string   `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	DateTime             string   `protobuf:"bytes,5,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Location             string   `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePwdRes) Reset()         { *m = ChangePwdRes{} }
func (m *ChangePwdRes) String() string { return proto.CompactTextString(m) }
func (*ChangePwdRes) ProtoMessage()    {}
func (*ChangePwdRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *ChangePwdRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePwdRes.Unmarshal(m, b)
}
func (m *ChangePwdRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePwdRes.Marshal(b, m, deterministic)
}
func (m *ChangePwdRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePwdRes.Merge(m, src)
}
func (m *ChangePwdRes) XXX_Size() int {
	return xxx_messageInfo_ChangePwdRes.Size(m)
}
func (m *ChangePwdRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePwdRes.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePwdRes proto.InternalMessageInfo

func (m *ChangePwdRes) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *ChangePwdRes) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *ChangePwdRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChangePwdRes) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ChangePwdRes) GetDateTime() string {
	if m != nil {
		return m.DateTime
	}
	return ""
}

func (m *ChangePwdRes) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

// ForgotPassword
type ForgotPasswordReq struct {
	Req                  *BaseReq `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Resend               bool     `protobuf:"varint,3,opt,name=resend,proto3" json:"resend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordReq) Reset()         { *m = ForgotPasswordReq{} }
func (m *ForgotPasswordReq) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordReq) ProtoMessage()    {}
func (*ForgotPasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *ForgotPasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordReq.Unmarshal(m, b)
}
func (m *ForgotPasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordReq.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordReq.Merge(m, src)
}
func (m *ForgotPasswordReq) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordReq.Size(m)
}
func (m *ForgotPasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordReq proto.InternalMessageInfo

func (m *ForgotPasswordReq) GetReq() *BaseReq {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *ForgotPasswordReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ForgotPasswordReq) GetResend() bool {
	if m != nil {
		return m.Resend
	}
	return false
}

type ForgotPasswordRes struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	TemplateId           string   `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRes) Reset()         { *m = ForgotPasswordRes{} }
func (m *ForgotPasswordRes) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRes) ProtoMessage()    {}
func (*ForgotPasswordRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *ForgotPasswordRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRes.Unmarshal(m, b)
}
func (m *ForgotPasswordRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRes.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRes.Merge(m, src)
}
func (m *ForgotPasswordRes) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRes.Size(m)
}
func (m *ForgotPasswordRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRes.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRes proto.InternalMessageInfo

func (m *ForgotPasswordRes) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *ForgotPasswordRes) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *ForgotPasswordRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ForgotPasswordRes) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ForgotPasswordRes) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// CheckAuthenticationCode
type CheckAuthenticationCodeReq struct {
	Req                  *BaseReq `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAuthenticationCodeReq) Reset()         { *m = CheckAuthenticationCodeReq{} }
func (m *CheckAuthenticationCodeReq) String() string { return proto.CompactTextString(m) }
func (*CheckAuthenticationCodeReq) ProtoMessage()    {}
func (*CheckAuthenticationCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{13}
}

func (m *CheckAuthenticationCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAuthenticationCodeReq.Unmarshal(m, b)
}
func (m *CheckAuthenticationCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAuthenticationCodeReq.Marshal(b, m, deterministic)
}
func (m *CheckAuthenticationCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAuthenticationCodeReq.Merge(m, src)
}
func (m *CheckAuthenticationCodeReq) XXX_Size() int {
	return xxx_messageInfo_CheckAuthenticationCodeReq.Size(m)
}
func (m *CheckAuthenticationCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAuthenticationCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAuthenticationCodeReq proto.InternalMessageInfo

func (m *CheckAuthenticationCodeReq) GetReq() *BaseReq {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *CheckAuthenticationCodeReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CheckAuthenticationCodeReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CheckAuthenticationCodeRes struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAuthenticationCodeRes) Reset()         { *m = CheckAuthenticationCodeRes{} }
func (m *CheckAuthenticationCodeRes) String() string { return proto.CompactTextString(m) }
func (*CheckAuthenticationCodeRes) ProtoMessage()    {}
func (*CheckAuthenticationCodeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{14}
}

func (m *CheckAuthenticationCodeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAuthenticationCodeRes.Unmarshal(m, b)
}
func (m *CheckAuthenticationCodeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAuthenticationCodeRes.Marshal(b, m, deterministic)
}
func (m *CheckAuthenticationCodeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAuthenticationCodeRes.Merge(m, src)
}
func (m *CheckAuthenticationCodeRes) XXX_Size() int {
	return xxx_messageInfo_CheckAuthenticationCodeRes.Size(m)
}
func (m *CheckAuthenticationCodeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAuthenticationCodeRes.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAuthenticationCodeRes proto.InternalMessageInfo

func (m *CheckAuthenticationCodeRes) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// ResetPassword
type ResetPasswordReq struct {
	Req                  *BaseReq `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordReq) Reset()         { *m = ResetPasswordReq{} }
func (m *ResetPasswordReq) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordReq) ProtoMessage()    {}
func (*ResetPasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{15}
}

func (m *ResetPasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordReq.Unmarshal(m, b)
}
func (m *ResetPasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordReq.Marshal(b, m, deterministic)
}
func (m *ResetPasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordReq.Merge(m, src)
}
func (m *ResetPasswordReq) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordReq.Size(m)
}
func (m *ResetPasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordReq proto.InternalMessageInfo

func (m *ResetPasswordReq) GetReq() *BaseReq {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *ResetPasswordReq) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *ResetPasswordReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResetPasswordReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ResetPasswordRes struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	TemplateId           string   `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	DateTime             string   `protobuf:"bytes,5,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Location             string   `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRes) Reset()         { *m = ResetPasswordRes{} }
func (m *ResetPasswordRes) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRes) ProtoMessage()    {}
func (*ResetPasswordRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{16}
}

func (m *ResetPasswordRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRes.Unmarshal(m, b)
}
func (m *ResetPasswordRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRes.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRes.Merge(m, src)
}
func (m *ResetPasswordRes) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRes.Size(m)
}
func (m *ResetPasswordRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRes.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRes proto.InternalMessageInfo

func (m *ResetPasswordRes) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *ResetPasswordRes) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *ResetPasswordRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResetPasswordRes) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResetPasswordRes) GetDateTime() string {
	if m != nil {
		return m.DateTime
	}
	return ""
}

func (m *ResetPasswordRes) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "protobuf.UserInfo")
	proto.RegisterType((*CreateUserReq)(nil), "protobuf.CreateUserReq")
	proto.RegisterType((*CreateUserRes)(nil), "protobuf.CreateUserRes")
	proto.RegisterType((*ReadUserReq)(nil), "protobuf.ReadUserReq")
	proto.RegisterType((*ReadUserRes)(nil), "protobuf.ReadUserRes")
	proto.RegisterType((*UpdateUserReq)(nil), "protobuf.UpdateUserReq")
	proto.RegisterType((*UpdateUserRes)(nil), "protobuf.UpdateUserRes")
	proto.RegisterType((*DeleteUserReq)(nil), "protobuf.DeleteUserReq")
	proto.RegisterType((*DeleteUserRes)(nil), "protobuf.DeleteUserRes")
	proto.RegisterType((*ChangePwdReq)(nil), "protobuf.ChangePwdReq")
	proto.RegisterType((*ChangePwdRes)(nil), "protobuf.ChangePwdRes")
	proto.RegisterType((*ForgotPasswordReq)(nil), "protobuf.ForgotPasswordReq")
	proto.RegisterType((*ForgotPasswordRes)(nil), "protobuf.ForgotPasswordRes")
	proto.RegisterType((*CheckAuthenticationCodeReq)(nil), "protobuf.CheckAuthenticationCodeReq")
	proto.RegisterType((*CheckAuthenticationCodeRes)(nil), "protobuf.CheckAuthenticationCodeRes")
	proto.RegisterType((*ResetPasswordReq)(nil), "protobuf.ResetPasswordReq")
	proto.RegisterType((*ResetPasswordRes)(nil), "protobuf.ResetPasswordRes")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0xad, 0x53, 0x37, 0x75, 0x26, 0x49, 0xf5, 0x75, 0x3f, 0x68, 0x2d, 0xf7, 0x40, 0x6a, 0x10,
	0xe4, 0x54, 0xa4, 0xc2, 0x09, 0x09, 0xa9, 0x34, 0x08, 0x29, 0x12, 0x94, 0xc8, 0xd0, 0x4b, 0x55,
	0x29, 0x72, 0xb2, 0x93, 0xd6, 0xaa, 0xe3, 0x4d, 0x6d, 0xa7, 0x11, 0x77, 0x4e, 0x1c, 0xf9, 0x19,
	0x1c, 0xf8, 0x25, 0xfc, 0x24, 0x0e, 0x68, 0x77, 0xb3, 0xf1, 0xba, 0x89, 0xab, 0xa0, 0xb6, 0x12,
	0xa7, 0x78, 0x66, 0x76, 0xdf, 0xbc, 0x7d, 0xd9, 0x79, 0x0b, 0x30, 0x4e, 0x30, 0xde, 0x1b, 0xc5,
	0x2c, 0x65, 0xc4, 0x12, 0x3f, 0xbd, 0xf1, 0xc0, 0x81, 0x9e, 0x9f, 0xa0, 0xcc, 0xba, 0xbf, 0x0d,
	0xb0, 0x8e, 0x13, 0x8c, 0xdb, 0xd1, 0x80, 0x91, 0x0d, 0x28, 0x05, 0xd4, 0x36, 0x1a, 0x46, 0xd3,
	0xf4, 0x4a, 0x01, 0x25, 0x3b, 0x50, 0x19, 0x8c, 0xc3, 0xb0, 0x1b, 0xf9, 0x43, 0xb4, 0x4b, 0x0d,
	0xa3, 0x59, 0xf1, 0x2c, 0x9e, 0x38, 0xf2, 0x87, 0x48, 0x1e, 0xc0, 0x1a, 0x0e, 0xfd, 0x20, 0xb4,
	0x57, 0x45, 0x41, 0x06, 0xc4, 0x01, 0x6b, 0xe4, 0x27, 0xc9, 0x84, 0xc5, 0xd4, 0x36, 0xe5, 0x0e,
	0x15, 0xf3, 0x1a, 0xe7, 0x23, 0xd0, 0xd6, 0x64, 0x4d, 0xc5, 0x1c, 0x2d, 0xc4, 0x2b, 0x0c, 0xed,
	0x72, 0xc3, 0x68, 0xd6, 0x3d, 0x19, 0x10, 0x02, 0x66, 0xcc, 0x42, 0xb4, 0xd7, 0x45, 0x52, 0x7c,
	0x73, 0x94, 0x0b, 0xfc, 0x92, 0xa4, 0x2c, 0x46, 0xdb, 0x92, 0x28, 0x2a, 0x26, 0xcf, 0xe1, 0x7f,
	0x8c, 0xfc, 0x5e, 0x88, 0xdd, 0x88, 0xa5, 0xc1, 0x20, 0xe8, 0xfb, 0x69, 0xc0, 0x22, 0xbb, 0xd2,
	0x30, 0x9a, 0x96, 0x47, 0x64, 0xe9, 0x48, 0xab, 0xb8, 0xa7, 0x50, 0x6f, 0xc5, 0xe8, 0xa7, 0xc8,
	0x35, 0xf0, 0xf0, 0x92, 0x3c, 0x86, 0xd5, 0x18, 0x2f, 0x85, 0x06, 0xd5, 0xfd, 0xcd, 0x3d, 0xa5,
	0xd9, 0xde, 0xa1, 0x9f, 0xa0, 0x87, 0x97, 0x1e, 0xaf, 0x92, 0xa7, 0x60, 0x72, 0xe2, 0x42, 0x92,
	0xea, 0x3e, 0xc9, 0x56, 0x29, 0x25, 0x3d, 0x51, 0x77, 0x3f, 0xe6, 0xd1, 0x13, 0xb2, 0x05, 0xe5,
	0x18, 0x93, 0x71, 0x98, 0x8a, 0x06, 0x96, 0x37, 0x8d, 0x96, 0x06, 0x3c, 0x81, 0xaa, 0x87, 0x3e,
	0xbd, 0x17, 0xb2, 0x1f, 0x74, 0xec, 0xdb, 0x53, 0x3d, 0x85, 0xfa, 0xf1, 0x88, 0xde, 0xa3, 0xb2,
	0x3a, 0xfa, 0x9d, 0xd0, 0x7d, 0x8b, 0x21, 0xde, 0x1f, 0x5d, 0x1d, 0xfd, 0xf6, 0x74, 0xbf, 0x1b,
	0x50, 0x6b, 0x9d, 0xfb, 0xd1, 0x19, 0x76, 0x26, 0x74, 0x69, 0xba, 0xdb, 0xb0, 0xce, 0x77, 0x77,
	0x03, 0x2a, 0x1a, 0xd4, 0xbd, 0x32, 0x0f, 0xdb, 0x94, 0xec, 0x42, 0x8d, 0x85, 0xb4, 0x3b, 0x9b,
	0x5c, 0x39, 0xd2, 0x55, 0x16, 0xd2, 0x8e, 0x1a, 0xde, 0x5d, 0xa8, 0x45, 0x38, 0xe9, 0x5e, 0x1b,
	0xee, 0x6a, 0x84, 0x13, 0xb5, 0xc4, 0xfd, 0x91, 0x27, 0x55, 0x7c, 0xca, 0x47, 0x50, 0x4d, 0x71,
	0x38, 0x0a, 0xfd, 0x14, 0x15, 0x97, 0x8a, 0x07, 0x2a, 0xd5, 0xa6, 0x7c, 0xee, 0x85, 0x4b, 0x48,
	0x1e, 0x66, 0x94, 0xf3, 0x1b, 0x53, 0xf7, 0x9b, 0x1d, 0xa8, 0xf0, 0x6b, 0xd0, 0x4d, 0x83, 0xcc,
	0x54, 0x78, 0xe2, 0x73, 0x30, 0x14, 0x56, 0x11, 0xb2, 0xa9, 0x07, 0x94, 0x65, 0x4d, 0xc5, 0xee,
	0x00, 0x36, 0xdf, 0xb1, 0xf8, 0x8c, 0xa5, 0x8a, 0xfe, 0xd2, 0x2a, 0xce, 0x88, 0x94, 0x74, 0x22,
	0xf2, 0xac, 0x18, 0x49, 0xf1, 0xe4, 0x59, 0x31, 0xa2, 0xee, 0x37, 0x63, 0xbe, 0xd1, 0x1d, 0x2b,
	0x43, 0xc0, 0xec, 0x33, 0x8a, 0x53, 0x61, 0xc4, 0x77, 0x46, 0x72, 0x4d, 0x23, 0xe9, 0x5e, 0x80,
	0xd3, 0x3a, 0xc7, 0xfe, 0xc5, 0x9b, 0x71, 0x7a, 0x8e, 0x51, 0x3a, 0x75, 0xc1, 0x16, 0xa3, 0xb8,
	0xf4, 0xe9, 0x55, 0xb3, 0xd2, 0xa2, 0x66, 0xfa, 0x53, 0xe0, 0xbe, 0xbc, 0xa1, 0x59, 0xa1, 0x02,
	0xee, 0x57, 0x03, 0xfe, 0xf3, 0x30, 0xc1, 0xbf, 0xff, 0x5f, 0xae, 0xdf, 0xd0, 0xd2, 0xdc, 0x0d,
	0x2d, 0x78, 0xb3, 0x16, 0xe8, 0xe7, 0xfe, 0x9c, 0xa7, 0xf1, 0x4f, 0xdf, 0xe7, 0xfd, 0x5f, 0x26,
	0xac, 0x73, 0x93, 0xf8, 0x74, 0xd5, 0x27, 0x07, 0x00, 0xd9, 0xbb, 0x43, 0xb6, 0x33, 0xbd, 0x72,
	0x6f, 0x9d, 0x53, 0x50, 0x48, 0xdc, 0x15, 0xf2, 0x0a, 0x2c, 0xf5, 0x18, 0x90, 0x87, 0xd9, 0x32,
	0xed, 0xf1, 0x71, 0x16, 0xa6, 0xf9, 0xde, 0x03, 0x80, 0xcc, 0x9b, 0xf5, 0xee, 0xb9, 0xf7, 0xc0,
	0x29, 0x28, 0x4c, 0x11, 0x32, 0xbb, 0xd4, 0x11, 0x72, 0x16, 0xed, 0x14, 0x14, 0x38, 0xc2, 0x6b,
	0xa8, 0xcc, 0x9c, 0x88, 0x6c, 0x69, 0xe7, 0xd4, 0x3c, 0xd3, 0x59, 0x9c, 0xe7, 0xdb, 0xdf, 0xc3,
	0x46, 0x7e, 0x66, 0xc9, 0x4e, 0xb6, 0x76, 0xce, 0x36, 0x9c, 0x1b, 0x8a, 0x1c, 0xed, 0x0c, 0xb6,
	0x0b, 0x06, 0x81, 0x3c, 0xd1, 0x29, 0x14, 0x0d, 0xa6, 0xb3, 0xcc, 0x2a, 0xde, 0xa8, 0x0d, 0xf5,
	0xdc, 0x9d, 0x25, 0x8e, 0xfe, 0x1f, 0xe5, 0x67, 0xca, 0x29, 0xae, 0x25, 0xee, 0xca, 0xe1, 0x33,
	0xa8, 0xf5, 0xd9, 0x70, 0xb6, 0xe4, 0xb0, 0xc2, 0xb5, 0xed, 0xf0, 0xa8, 0x63, 0x9c, 0x80, 0x4a,
	0x8f, 0x7a, 0xbd, 0xb2, 0xf8, 0x7e, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0x38, 0x12, 0xca, 0xb2,
	0x6b, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserSvcClient is the client API for UserSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSvcClient interface {
	CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserRes, error)
	ReadUser(ctx context.Context, in *ReadUserReq, opts ...grpc.CallOption) (*ReadUserRes, error)
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRes, error)
	DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserRes, error)
	ChangePwd(ctx context.Context, in *ChangePwdReq, opts ...grpc.CallOption) (*ChangePwdRes, error)
	// All below funcs are used for forgotting password flow
	ForgotPassword(ctx context.Context, in *ForgotPasswordReq, opts ...grpc.CallOption) (*ForgotPasswordRes, error)
	CheckAuthenticationCode(ctx context.Context, in *CheckAuthenticationCodeReq, opts ...grpc.CallOption) (*CheckAuthenticationCodeRes, error)
	ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*ResetPasswordRes, error)
}

type userSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserSvcClient(cc grpc.ClientConnInterface) UserSvcClient {
	return &userSvcClient{cc}
}

func (c *userSvcClient) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserRes, error) {
	out := new(CreateUserRes)
	err := c.cc.Invoke(ctx, "/protobuf.UserSvc/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) ReadUser(ctx context.Context, in *ReadUserReq, opts ...grpc.CallOption) (*ReadUserRes, error) {
	out := new(ReadUserRes)
	err := c.cc.Invoke(ctx, "/protobuf.UserSvc/ReadUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRes, error) {
	out := new(UpdateUserRes)
	err := c.cc.Invoke(ctx, "/protobuf.UserSvc/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserRes, error) {
	out := new(DeleteUserRes)
	err := c.cc.Invoke(ctx, "/protobuf.UserSvc/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) ChangePwd(ctx context.Context, in *ChangePwdReq, opts ...grpc.CallOption) (*ChangePwdRes, error) {
	out := new(ChangePwdRes)
	err := c.cc.Invoke(ctx, "/protobuf.UserSvc/ChangePwd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) ForgotPassword(ctx context.Context, in *ForgotPasswordReq, opts ...grpc.CallOption) (*ForgotPasswordRes, error) {
	out := new(ForgotPasswordRes)
	err := c.cc.Invoke(ctx, "/protobuf.UserSvc/ForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) CheckAuthenticationCode(ctx context.Context, in *CheckAuthenticationCodeReq, opts ...grpc.CallOption) (*CheckAuthenticationCodeRes, error) {
	out := new(CheckAuthenticationCodeRes)
	err := c.cc.Invoke(ctx, "/protobuf.UserSvc/CheckAuthenticationCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*ResetPasswordRes, error) {
	out := new(ResetPasswordRes)
	err := c.cc.Invoke(ctx, "/protobuf.UserSvc/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSvcServer is the server API for UserSvc service.
type UserSvcServer interface {
	CreateUser(context.Context, *CreateUserReq) (*CreateUserRes, error)
	ReadUser(context.Context, *ReadUserReq) (*ReadUserRes, error)
	UpdateUser(context.Context, *UpdateUserReq) (*UpdateUserRes, error)
	DeleteUser(context.Context, *DeleteUserReq) (*DeleteUserRes, error)
	ChangePwd(context.Context, *ChangePwdReq) (*ChangePwdRes, error)
	// All below funcs are used for forgotting password flow
	ForgotPassword(context.Context, *ForgotPasswordReq) (*ForgotPasswordRes, error)
	CheckAuthenticationCode(context.Context, *CheckAuthenticationCodeReq) (*CheckAuthenticationCodeRes, error)
	ResetPassword(context.Context, *ResetPasswordReq) (*ResetPasswordRes, error)
}

// UnimplementedUserSvcServer can be embedded to have forward compatible implementations.
type UnimplementedUserSvcServer struct {
}

func (*UnimplementedUserSvcServer) CreateUser(ctx context.Context, req *CreateUserReq) (*CreateUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserSvcServer) ReadUser(ctx context.Context, req *ReadUserReq) (*ReadUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadUser not implemented")
}
func (*UnimplementedUserSvcServer) UpdateUser(ctx context.Context, req *UpdateUserReq) (*UpdateUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserSvcServer) DeleteUser(ctx context.Context, req *DeleteUserReq) (*DeleteUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserSvcServer) ChangePwd(ctx context.Context, req *ChangePwdReq) (*ChangePwdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePwd not implemented")
}
func (*UnimplementedUserSvcServer) ForgotPassword(ctx context.Context, req *ForgotPasswordReq) (*ForgotPasswordRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgotPassword not implemented")
}
func (*UnimplementedUserSvcServer) CheckAuthenticationCode(ctx context.Context, req *CheckAuthenticationCodeReq) (*CheckAuthenticationCodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAuthenticationCode not implemented")
}
func (*UnimplementedUserSvcServer) ResetPassword(ctx context.Context, req *ResetPasswordReq) (*ResetPasswordRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}

func RegisterUserSvcServer(s *grpc.Server, srv UserSvcServer) {
	s.RegisterService(&_UserSvc_serviceDesc, srv)
}

func _UserSvc_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserSvc/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).CreateUser(ctx, req.(*CreateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_ReadUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).ReadUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserSvc/ReadUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).ReadUser(ctx, req.(*ReadUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserSvc/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).UpdateUser(ctx, req.(*UpdateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserSvc/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).DeleteUser(ctx, req.(*DeleteUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_ChangePwd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePwdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).ChangePwd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserSvc/ChangePwd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).ChangePwd(ctx, req.(*ChangePwdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserSvc/ForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).ForgotPassword(ctx, req.(*ForgotPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_CheckAuthenticationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAuthenticationCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).CheckAuthenticationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserSvc/CheckAuthenticationCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).CheckAuthenticationCode(ctx, req.(*CheckAuthenticationCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserSvc/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).ResetPassword(ctx, req.(*ResetPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.UserSvc",
	HandlerType: (*UserSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserSvc_CreateUser_Handler,
		},
		{
			MethodName: "ReadUser",
			Handler:    _UserSvc_ReadUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserSvc_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserSvc_DeleteUser_Handler,
		},
		{
			MethodName: "ChangePwd",
			Handler:    _UserSvc_ChangePwd_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _UserSvc_ForgotPassword_Handler,
		},
		{
			MethodName: "CheckAuthenticationCode",
			Handler:    _UserSvc_CheckAuthenticationCode_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _UserSvc_ResetPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
